name: BTP QA Bug Report
description: Report a bug found during QA
title: "[QA]: (This will get replaced automatically)"
labels: ["QA"]

body:
  - type: dropdown
    id: qa_category
    attributes:
      label: QA Category
      description: Select the type of QA testing this issue relates to.
      options:
        - Functionality Testing
        - Responsive and Cross-browser Testing
        - Accessibility
        - Load Testing
    validations:
      required: true

  - type: dropdown
    id: issue_category
    attributes:
      label: Issue Type
      description: What didn't work? 
      options:
      - Breaking Functionality (Didn't Work At All!)
      - Functional Deviation (Didn't Work as Expected!)
      - Visual / Design (Didn't Look Right!)
      - Copy / Content (The Words Are Wrong!)
    validations:
      required: true

  - type: input
    id: urls
    attributes:
      label: URL(s)
      description: Paste one or more URLs (separate with commas or new lines).
      placeholder: https://example.com/page
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Actual behavior vs expected behavior?
      description: What’s wrong? Be specific and describe impact.
      placeholder: "Actual:
        The page reloads and shows a blank screen after clicking Submit.

        Expected:
        A confirmation message should appear and the form should be saved."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce?
      description: Numbered steps are best.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true

  - type: dropdown
    id: account_state
    attributes:
      label: Account State
      description: What was the user’s authentication state?
      options:
        - Logged In
        - Logged Out
        - Logged In and Logged Out
        - N/A
    validations:
      required: true

  - type: checkboxes
    id: browsers
    attributes:
      label: Browser(s)
      description: Check all that apply.
      options:
        - label: Chrome
        - label: Edge
        - label: Firefox
        - label: Safari
    validations:
      required: true

  - type: checkboxes
    id: devices
    attributes:
      label: Device(s)
      description: Check all that apply.
      options:
        - label: Mac Desktop / Laptop
        - label: Windows Desktop / Laptop
        - label: iPhone
        - label: Android Phone
        - label: iPad
        - label: Android Tablet
    validations:
      required: true

  - type: checkboxes
    id: specific_os
    attributes:
      label: Specific Operating System(s)
      description: Check all that apply.
      options:
        - label: Mac OS 26.x Tahoe
        - label: Mac OS 15.x Sequoia
        - label: Mac OS 14.x Sonoma
        - label: Mac OS 13.x Ventura
        - label: Mac OS 12.x Monterey
        - label: Mac OS 11.x Big Sur
        - label: Windows 11.x
        - label: Windows 10.x
        - label: iOS 26.x
        - label: iOS 18.x
        - label: iOS 17.x
        - label: iPadOS 26.x
        - label: iPadOS 18.x
        - label: iPadOS 17.x
        - label: Android 16
        - label: Android 15
        - label: Android 14
    validations:
      required: true

  - type: checkboxes
    id: isp_speed
    attributes:
      label: General ISP Speed
      description: Approximate internet speed at the time of testing.
      options:
        - label: Slow (< 10 Mbps)
        - label: Average (10–100 Mbps)
        - label: Fast (> 100 Mbps)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Screenshots / Video (if helpful)
        Add files by dragging them into this issue after it’s created, or paste images directly into the text box.
